@startuml
!include <C4/C4_Container>

Person(personPecuarista, "Pecuarista", "Usuário Visualiza o DashBoard do Sistema em um página web. ")
Person(personVaqueiro, "Vaqueiro", "Usuário Responsavel pelo registro de pesos e numero do brinco de bovinos e ")

Container(containerRoman, "Romaneio de Bovinos", "WEBAPP", "Sistema de controle de pesagem de animais e entrega de relatorio deTotal e Media @ ")


Rel(personPecuarista, containerRoman, "Label", "Navegador de computador pessoal")
Rel(personVaqueiro, containerRoman, "Label", "Navegando de um Mobile")

@enduml
