@startuml Diagrama_de_Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' Título do Diagrama C4 Container
title Diagrama de Containers - Sistema de Romaneio de Bovinos

' Pessoas / Atores
Person(Vaqueiro, "Vaqueiro", "Resposável por registrar os pesos e brincos de animais")
Person(Pecuarista, "Pecuarista", "Visualizar o historio de pesagem e um dashboard dos pesos")

' 
' Limite da Aplicação (O Sistema de Vendas)
System_Boundary(sistema, "Sistema de Romaneio Online") {
    Container(Registro, "Aplicativo Mobile/ Página Web", "Flutter", "Interface do cliente para navegação e checkout no navegador.")
    Container(DashBoard, "Página Web", "CSS / HTML / Python / Flask", "Interface do Administrador para visualizar um Dashboard.")
     
    ContainerDb(database, "Banco de Dados Relacional", "SQLite", "Armazena dados de clientes, produtos, pedidos e transações.")
}

' Relacionamentos
Rel(Pecuarista, Registro, "Usa", "HTTPS")
Rel(Vaqueiro, DashBoard, "Usa", "HTTPS")

Rel(Registro, database, "Lê e escreve dados em", "SQLAlchemy")
Rel(DashBoard, database, "Lê e escreve dados em", "SQLAlchemy")



@enduml